name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends ffmpeg && apt-get clean && pip3 install --no-cache-dir --upgrade --requirement requirements.txt && bash start
